### ISSUE TITLE
timeout with withdraw

### ISSUE THREAD

**Issue by Igorlende** [zksync-sdk/zksync2-python#12]
https://github.com/zksync-sdk/zksync2-python/blob/master/examples/11_withdrawal.py

I try run this example and get errors like this:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\zksync2\module\zksync_module.py", line 383, in wait_finalized
    _timeout.sleep(poll_latency)
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\web3\_utils\threads.py", line 99, in sleep
    self.check()
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\web3\_utils\threads.py", line 92, in check
    raise self
web3._utils.threads.Timeout: 240 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\zksync\main2.py", line 141, in <module>
    example_withdrawal(0.0001)
  File "C:\Users\User\PycharmProjects\zksync\main2.py", line 70, in example_withdrawal
    zks_receipt = web3.zksync.wait_finalized(tx_hash, timeout=240, poll_latency=0.5)
  File "C:\Users\User\PycharmProjects\zksync\venv\lib\site-packages\zksync2\module\zksync_module.py", line 387, in wait_finalized
    raise TimeExhausted(
web3.exceptions.TimeExhausted: Transaction HexBytes('0x8a47e826e7ae59fb9034b05b5af1ef3a0ad160ba1c50930da8d2e7b116fcbfa9') is not in the chain after 240 seconds

**Comment by andreidev1** [comment]
Are you connected to a remote test network or a local network ?

**Comment by Igorlende** [comment]
remote
ZKSYNC_TEST_URL = "https://zksync2-testnet.zksync.dev"
ETH_TEST_URL = "https://rpc.ankr.com/eth_goerli"

**Comment by Igorlende** [comment]
remote
ZKSYNC_TEST_URL = "https://zksync2-testnet.zksync.dev"
ETH_TEST_URL = "https://rpc.ankr.com/eth_goerli"

**Comment by danijelTxFusion** [comment]
Withdrawal on testnet takes around 11 hours to complete. So there is no point to wait that long in program, so program should end when withdrawal transaction is finished. Do not forget that finalize withdrawal needs to be executed after withdrawal. So the workflow is following. 

- Execute Withdraw script.
- Wait for transaction to be completed.
- Execute Finalize Withdraw srcript.

Here are the examples:

- [Withdrawal](https://github.com/zksync-sdk/zksync2-python/blob/master/examples/09_withdrawal.py)
- [Finalize Withdrawal](https://github.com/zksync-sdk/zksync2-python/blob/master/examples/10_finalize_withdrawal.py)
