### ISSUE TITLE
Missing field gasPerPubdata

### ISSUE THREAD

**Issue by firke** [zksync-sdk/zksync2-python#5]
When trying to run example transfers from the readme, getting the following error:
```
Traceback (most recent call last):
  File "/Users/user/run.py", line 31, in <module>
    zksync.transfer(zksync_web3, account, 0.0000001, item)
  File "/Users/user/run.py", line 46, in transfer
    estimate_gas = zksync_web3.zksync.eth_estimate_gas(tx_func_call.tx)
  File "/Users/user/.pyenv/versions/3.10.2/lib/python3.10/site-packages/zksync2/module/zksync_module.py", line 284, in eth_estimate_gas
    return self._eth_estimate_gas(tx)
  File "/Users/user/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/Users/user/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/Users/user/.pyenv/versions/3.10.2/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32602, 'message': 'Invalid params: missing field `gasPerPubdata`.'}
```

**Comment by hausuresh** [comment]
Same issue
ValueError: {'code': -32602, 'message': 'Invalid params: missing field `gasPerPubdata`.'}
When execute function transfer_to_self

**Comment by possib1e** [comment]
Same issue, python 3.9

**Comment by Shaneue** [comment]
Same issue

**Comment by vyastrebovvareger** [comment]
new version has been released. Please have a try with the latest one
