### ISSUE TITLE
Missing l1EthDefaultBridge

### ISSUE THREAD

**Issue by jackliu8722** [zksync-sdk/zksync2-python#6]
when I run the example deposit, I got the error as follow:
Traceback (most recent call last):
  File "/Users/jackliu/workspace/zkSync/dev-sync/deposit.py", line 44, in <module>
    deposit()
  File "/Users/jackliu/workspace/zkSync/dev-sync/deposit.py", line 24, in deposit
    eth_provider = EthereumProvider.build_ethereum_provider(
  File "/Users/jackliu/workspace/zkSync/dev-sync/venv/lib/python3.9/site-packages/zksync2/provider/eth_provider.py", line 36, in build_ethereum_provider
    bridge_contracts: BridgeAddresses = zksync.zksync.zks_get_bridge_contracts()
  File "/Users/jackliu/workspace/zkSync/dev-sync/venv/lib/python3.9/site-packages/zksync2/module/zksync_module.py", line 271, in zks_get_bridge_contracts
    return self._zks_get_bridge_contracts()
  File "/Users/jackliu/workspace/zkSync/dev-sync/venv/lib/python3.9/site-packages/web3/module.py", line 61, in caller
    return apply_result_formatters(result_formatters, result)
  File "cytoolz/functoolz.pyx", line 249, in cytoolz.functoolz.curry.__call__
  File "/Users/jackliu/workspace/zkSync/dev-sync/venv/lib/python3.9/site-packages/web3/module.py", line 38, in apply_result_formatters
    formatted_result = pipe(result, result_formatters)
  File "cytoolz/functoolz.pyx", line 666, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 641, in cytoolz.functoolz.c_pipe
  File "cytoolz/functoolz.pyx", line 502, in cytoolz.functoolz.Compose.__call__
  File "/Users/jackliu/workspace/zkSync/dev-sync/venv/lib/python3.9/site-packages/zksync2/module/zksync_module.py", line 105, in to_bridge_address
    return BridgeAddresses(l1_eth_default_bridge=HexStr(to_checksum_address(t["l1EthDefaultBridge"])),
KeyError: 'l1EthDefaultBridge'

**Comment by vyastrebovvareger** [comment]
Hello guys. There is coming soon the new release with most fixes relate to the latest changes of the ZkSync node side.
the most up to date is the develop branch

**Comment by vyastrebovvareger** [comment]
New version has been released. Please use the updated one
